Add sensors for monitoring F-engine rx health
ska-sa/katgpucbf pull request #476
Opened 2022-11-21 10:11 UTC by bmerry

Checklist (if not applicable, edit to add `(N/A)` and mark as done):

- [x] If dependencies are added/removed: update ``setup.cfg`` and appropriate requirements files
- [x] (N/A) If modules are added/removed: use sphinx-apidoc to update files in ``doc/``
- [x] Ensure copyright notices are present and up-to-date
- [x] (N/A) If qualification tests are changed: attach a sample qualification report
- [x] (N/A) If design has changed: ensure documentation is up to date

Closes NGC-802, NGC-838 and NGC-839.

2022-11-21 11:41 UTC, james-smith-za requested changes
Overall I like it.
Just one nit-pick about a docstring which doesn't read so nicely (to me).

2022-11-21 12:22 UTC, bmerry commented on setup.cfg
> +    async-solipsism
Glad you like it :-) It tickled my fancy when I came up with it.

2022-11-21 12:34 UTC, bmerry commented on src/katgpucbf/utils.py
> +    is no need to cancel it. Alternatively, keep a reference and use
Is it better now?

2022-11-21 12:42 UTC, bmerry commented
I'm thinking that a fixed timeout might not be the best approach, because with sufficiently large chunks or sufficiently low bandwidth, the time between chunks could be greater than the timeout. I think a better solution is to set the timeout to the expected time for, say, 10 chunks.

2022-11-21 12:59 UTC, james-smith-za commented on src/katgpucbf/utils.py
> +    is no need to cancel it. Alternatively, keep a reference and use
Much, thank you.

2022-11-21 12:59 UTC, james-smith-za commented
> I'm thinking that a fixed timeout might not be the best approach, because with sufficiently large chunks or sufficiently low bandwidth, the time between chunks could be greater than the timeout. I think a better solution is to set the timeout to the expected time for, say, 10 chunks.

I don't object to this in principle. You'd just need a bit of logic to work out how long that ends up being.

2022-11-21 19:34 UTC, amishatishpatel approved these changes
Honestly, I can't find any holes in your plot here. Very cool, looking forward to using it.

Will give it another glance in the morning in case I missed anything/if James spots something.

2022-11-21 19:34 UTC, amishatishpatel commented on src/katgpucbf/fgpu/recv.py
> +        missing_sensors: list[aiokatcp.Sensor] = [
I see you've added empty lines in fgpu's `Engine::_populate_sensors` to separate the concerns
* Might I request the same here after you've created the 'normal' `rx-time` sensors (please)?

2022-11-22 07:41 UTC, bmerry commented on test/fgpu/test_recv.py
> +        return make_sensors(1e6)  # Large timeout so that it doesn't affect the test
> It also literally reads as if we're instructing it to make one million sensors.

I hope you're also reading that like [this](https://dailyhaymaker.com/wp-content/uploads/2014/01/drevil.png). Good point though, I'll update it.

2022-11-22 08:00 UTC, james-smith-za approved these changes
Only one observation but I don't feel strongly about it either way. I'm happy to merge.

2022-11-22 08:19 UTC, bmerry commented on src/katgpucbf/fgpu/recv.py
> +            sensors.add(sensor)
Someone might ask for rx-missing-timestamp.

2022-11-22 08:19 UTC, merged