Rename f-engine sensors hierarchically
ska-sa/katgpucbf pull request #496
Opened 2023-01-05 13:31 UTC by james-smith-za

The KATCP guidelines (and our CAM ICD, but this is less important because the F-engines are not directly exposed to CAM) recommend using fullstops for hierarchical separation and hyphens for word separation in sensor names.

This change separates stream-relevant (i.e. per-pol) labels from the underlying.

E.g. "input{pol}-eq" -> "input{pol}.eq"

Addresses NGC-854

(Requires https://github.com/ska-sa/katsdpcontroller/pull/651 on the controller side.)

Checklist (if not applicable, edit to add `(N/A)` and mark as done):

- [x] (N/A) If dependencies are added/removed: update `setup.cfg` and `.pre-commit-config.yaml`
- [x] (N/A) If modules are added/removed: use sphinx-apidoc to update files in `doc/`
- [x] Ensure copyright notices are present and up-to-date
- [x] (N/A) If qualification tests are changed: attach a sample qualification report
- [x] (N/A) If design has changed: ensure documentation is up to date
- [x] If ICD-defined sensors have been added: update `fake_servers.py` in katsdpcontroller to match

2023-01-10 07:14 UTC, bmerry requested changes
The changes you've made look good, but I still see this line in qualification/antenna_channelised_voltage/test_delay.py:
```python
return literal_eval(correlator.sensors[f"antenna_channelised_voltage-{label}-delay"].value.decode())
```

2023-01-13 06:40 UTC, bmerry approved these changes
LGTM. I assume you've run a qualification test to check that it all works.

2023-01-13 06:40 UTC, bmerry commented on qualification/antenna_channelised_voltage/test_delay.py
> +        return literal_eval(correlator.sensors[f"antenna_channelised_voltage.{label}-delay"].value.decode())
Shouldn't this be
```suggestion
        return literal_eval(correlator.sensors[f"antenna_channelised_voltage.{label}.delay"].value.decode())
```

2023-01-16 09:54 UTC, amishatishpatel commented
> I assume you've run a qualification test to check that it all works.

My apologies, for some reason I thought Jenkins would've told me if there were any issues qualification-related. Did a few runs now and made updates accordingly.

2023-01-16 10:54 UTC, bmerry approved these changes
Looks good, modulo the suggestion I had on Mattermost about removing the "input." prefix from xbgpu sensors.

2023-01-17 07:16 UTC, merged