Make provision for B-engine sensors
ska-sa/katgpucbf pull request #682
Opened 2024-02-09 10:58 UTC by amishatishpatel

There is no logic behind the sensors, this PR simply creates them in preparation for the logic.

The corresponding katsdpcontroller PR is at
* https://github.com/ska-sa/katsdpcontroller/pull/714

Checklist (if not applicable, edit to add `(N/A)` and mark as done):

- [ ] (N/A) If dependencies are added/removed: update `setup.cfg` and `.pre-commit-config.yaml`
- [ ] (N/A) If modules are added/removed: use `sphinx-apidoc -efo doc/ src/` to update files in `doc/`
- [ ] Ensure copyright notices are present and up-to-date
- [ ] (N/A) If qualification tests are changed: attach a sample qualification report
- [ ] (N/A) If design has changed: ensure documentation is up to date
- [ ] If ICD-defined sensors have been added: update `fake_servers.py` in katsdpcontroller to match

Closes NGC-447.

2024-02-09 12:03 UTC, james-smith-za commented on src/katgpucbf/xbgpu/engine.py
> +                    default=0.0,
Default gain of 0 doesn't make sense.
See: https://github.com/ska-sa/katgpucbf/blob/3b6cf9039403f5479e442b1d71f244f9820d4e1f/src/katgpucbf/xbgpu/engine.py#L334

2024-02-09 12:03 UTC, james-smith-za commented on src/katgpucbf/xbgpu/engine.py
> +                    initial_status=aiokatcp.Sensor.Status.NOMINAL,
Similarly, see here:
https://github.com/ska-sa/katgpucbf/blob/3b6cf9039403f5479e442b1d71f244f9820d4e1f/src/katgpucbf/xbgpu/engine.py#L332

2024-02-09 12:14 UTC, bmerry requested changes

2024-02-09 12:28 UTC, amishatishpatel commented on src/katgpucbf/xbgpu/engine.py
> +                    initial_status=aiokatcp.Sensor.Status.NOMINAL,
You know, I had that exact string in here, decided to remove it to get explicit feedback on the formatting 😅

2024-02-19 09:01 UTC, bmerry requested changes

2024-02-19 09:07 UTC, amishatishpatel commented on src/katgpucbf/xbgpu/engine.py
> +            default_delays_str = ", ".join(str(value) for value in self._delays[0].flatten())
Fair point! Change incoming.

2024-02-19 09:19 UTC, bmerry requested changes
Just a couple of typos - feel free to merge after fixing them.

2024-02-19 09:19 UTC, bmerry commented on src/katgpucbf/xbgpu/engine.py
> +                    # Cast to list first to add comma delimeter
```suggestion
                    # Cast to list first to add comma delimiter
```

2024-02-19 09:19 UTC, bmerry commented on src/katgpucbf/xbgpu/engine.py
> +                    "a delay [s] and phase [rad]: (loadmcnt, delay0, phase0, delay1,"
```suggestion
                    "a delay [s] and phase [rad]: (loadmcnt, delay0, phase0, delay1, "
```

2024-02-19 09:23 UTC, merged