Change `heap` to `batch` where appropriate
ska-sa/katgpucbf pull request #807
Opened 2024-06-21 14:10 UTC by james-smith-za

I kept the change to only internal interfaces, so basically the F-engine output.

I must confess I have mixed feelings about this. The smaller changes were straightforward enough but they left "spectra-per-heap" standing out like a sore thumb. So I changed that. But that brings the internal variable names out-of-sync with the ICD-defined sensor (which is implemented in the controller and really has no bearing here).

Checklist (if not applicable, edit to add `(N/A)` and mark as done):

- [x] (N/A) If dependencies are added/removed: update `setup.cfg` and `.pre-commit-config.yaml`
- [x] (N/A) If modules are added/removed: use `sphinx-apidoc -efo doc/ src/` to update files in `doc/`
- [x] Ensure copyright notices are present and up-to-date
- [x] (N/A) If qualification tests are changed: attach a sample qualification report
- [x] (N/A) If design has changed: ensure documentation is up to date
- [x] (N/A) If ICD-defined sensors have been added: update `fake_servers.py` in katsdpcontroller to match

Closes NGC-1235.

2024-06-24 09:18 UTC, bmerry commented
> I must confess I have mixed feelings about this. The smaller changes were straightforward enough but they left "spectra-per-heap" standing out like a sore thumb. So I changed that. But that brings the internal variable names out-of-sync with the ICD-defined sensor (which is implemented in the controller and really has no bearing here).

My feeling is that a "spectrum" is a collection of information about a signal at a range of frequencies at a single point in time. Thus, heaps do contain spectra - they're just spectra with less bandwidth than the spectra contained in batches. There is nothing fundamental about the bandwidth of a batch (in the narrowband case, it's not even the same as the digitised bandwidth), so I don't think that spectra-per-batch is any more "right" than spectra-per-heap. Hence, we might as well stick to spectra-per-heap for consistency with the ICD sensor (which in turn we should keep for backwards compatibility).

I'll hold off detailed review until we decide where to go with this.

2024-06-24 15:27 UTC, james-smith-za commented
OK. The argument is persuasive.
I kept the spectra-per-heap work to a single commit so I should just be able to reverse that commit.

2024-06-25 09:37 UTC, bmerry requested changes
The meat of it looks good - just some cleanup needed around your reverted change.

2024-06-25 09:37 UTC, bmerry commented on scratch/xbgpu/benchmarks/beamform_bench.py
> +    parser.add_argument("--spectra-per-batch", type=int, default=256, help="Spectra in each batch [%(default)s]")
I think you missed reverting this.

2024-06-25 09:37 UTC, bmerry commented on scratch/xbgpu/benchmarks/correlate_bench.py
> +    parser.add_argument("--spectra-per-batch", type=int, default=256, help="Spectra in each batch [%(default)s]")
I think you missed reverting this.

2024-06-25 09:37 UTC, bmerry commented on src/katgpucbf/fgpu/compute.py
> +# Copyright (c) 2020-2024, National Research Foundation (SARAO)
You've made copyright bumps on a number of files without changing them. Is that left over from the revert?

2024-06-25 09:37 UTC, bmerry commented on src/katgpucbf/fgpu/engine.py
> +                # We'v eexhausted the input buffer.
I prefer this the way it was...

2024-06-25 12:10 UTC, james-smith-za commented on src/katgpucbf/fgpu/engine.py
> +                # We'v eexhausted the input buffer.
oops.

2024-06-25 12:32 UTC, james-smith-za commented
Closing in favour of #810

2024-06-25 12:32 UTC, closed without merging